language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential swig
install:
  - python setup.py install
script:
  - cd pocketsphinx/swig/python/test
  - python ./config_test.py
  - python ./decoder_test.py
  - python ./fsg_test.py
  - python ./jsgf_test.py
  - python ./kws_test.py
  - python ./lattice_test.py
  - python ./lm_test.py